muvicinemas = [{'city': 'Riyadh',
  'duration': '2 h 50m',
  'genres': ['Adventure', 'Action', 'Thriller'],
  'language': 'ENGLISH',
  'rating': 'R15',
  'show_details': [{'cinema': [{'cinema': 'ScreenX',
                                'times': ['10:40 PM', '2:10 AM']},
                               {'cinema': 'XPERIENCE',
                                'times': ['10:00 PM', '1:40 AM']},
                               {'cinema': 'Standard',
                                'times': ['7:50 PM',
                                          '8:50 PM',
                                          '11:30 PM',
                                          '12:30 AM']}],
                    'location': 'Park Avenue'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['7:45 PM',
                                          '9:45 PM',
                                          '10:30 PM',
                                          '12:00 AM',
                                          '1:30 AM',
                                          '2:10 AM']}],
                    'location': 'The View'},
                   {'cinema': [{'cinema': 'Boutique Cinemas',
                                'times': ['8:50 PM', '12:30 AM']}],
                    'location': 'muvi Boutique - Tala Mall'},
                   {'cinema': [{'cinema': 'IMAX',
                                'times': ['8:10 PM', '11:50 PM']},
                               {'cinema': 'ScreenX',
                                'times': ['9:40 PM', '1:20 AM']},
                               {'cinema': 'Muvi Suites',
                                'times': ['9:20 PM',
                                          '10:40 PM',
                                          '11:30 PM',
                                          '1:00 AM']},
                               {'cinema': 'Standard',
                                'times': ['7:30 PM',
                                          '9:00 PM',
                                          '10:40 PM',
                                          '11:10 PM',
                                          '12:40 AM',
                                          '2:10 AM']}],
                    'location': 'U Walk'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['8:10 PM',
                                          '9:00 PM',
                                          '10:20 PM',
                                          '11:50 PM',
                                          '12:40 AM']}],
                    'location': 'Al Hamra Mall'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['9:00 PM',
                                          '9:40 PM',
                                          '10:45 PM',
                                          '11:30 PM',
                                          '12:40 AM',
                                          '1:20 AM']}],
                    'location': 'Salaam Mall'},
                   {'cinema': [{'cinema': 'ScreenX',
                                'times': ['10:20 PM', '2:00 AM']},
                               {'cinema': 'Muvi Suites',
                                'times': ['9:20 PM', '1:00 AM']},
                               {'cinema': 'Dolby Cinema®',
                                'times': ['9:50 PM', '1:30 AM']},
                               {'cinema': 'Standard',
                                'times': ['7:45 PM',
                                          '8:30 PM',
                                          '9:15 PM',
                                          '11:30 PM',
                                          '12:00 AM',
                                          '12:30 AM']}],
                    'location': 'Nakheel Mall'},
                   {'cinema': [{'cinema': 'Muvi Suites',
                                'times': ['8:40 PM', '10:30 PM', '12:30 AM']},
                               {'cinema': 'XPERIENCE',
                                'times': ['7:50 PM', '11:30 PM']}],
                    'location': 'Boulevard Riyadh City'}],
  'title': ['ميشن أيمبوسيبول: ذا فاينل ريكونينغ',
            'MISSION: IMPOSSIBLE - THE FINAL RECKONING']},
 {'city': 'Riyadh',
  'duration': '1 h 48m',
  'genres': ['Comedy', 'Adventure', 'Family'],
  'language': 'ENGLISH',
  'rating': '',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['7:40 PM', '10:30 PM', '1:10 AM']}],
                    'location': 'Park Avenue'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['9:00 PM', '9:40 PM', '11:20 PM']}],
                    'location': 'The View'},
                   {'cinema': [{'cinema': 'Boutique Cinemas',
                                'times': ['8:30 PM', '11:50 PM']}],
                    'location': 'muvi Boutique - Tala Mall'},
                   {'cinema': [{'cinema': 'Muvi Suites',
                                'times': ['7:30 PM', '10:10 PM', '1:20 AM']},
                               {'cinema': 'Dolby Cinema®',
                                'times': ['8:40 PM', '11:10 PM', '1:40 AM']},
                               {'cinema': 'Standard',
                                'times': ['7:40 PM',
                                          '9:20 PM',
                                          '11:50 PM',
                                          '2:10 AM']}],
                    'location': 'U Walk'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['9:30 PM']}],
                    'location': 'Al Hamra Mall'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['8:30 PM', '11:00 PM', '11:45 PM']}],
                    'location': 'Salaam Mall'},
                   {'cinema': [{'cinema': 'Muvi Suites',
                                'times': ['10:45 PM', '1:30 AM']},
                               {'cinema': 'Standard',
                                'times': ['9:00 PM', '11:30 PM']}],
                    'location': 'Nakheel Mall'},
                   {'cinema': [{'cinema': 'Muvi Suites',
                                'times': ['7:30 PM', '10:00 PM', '1:00 AM']},
                               {'cinema': 'Boutique Cinemas',
                                'times': ['7:20 PM', '12:20 AM']}],
                    'location': 'Boulevard Riyadh City'}],
  'title': ['ليلو وستيتش', 'LILO AND STITCH']},
 {'city': 'Riyadh',
  'duration': '1 h 48m',
  'genres': ['Family', 'Adventure', 'Comedy'],
  'language': 'EGYPTIAN',
  'rating': '',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['8:20 PM', '11:00 PM', '1:40 AM']}],
                    'location': 'Park Avenue'},
                   {'cinema': [{'cinema': 'Boutique Cinemas',
                                'times': ['11:00 PM']}],
                    'location': 'muvi Boutique - Tala Mall'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['7:30 PM', '10:00 PM', '1:30 AM']}],
                    'location': 'Salaam Mall'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['12:10 AM']}],
                    'location': 'Nakheel Mall'},
                   {'cinema': [{'cinema': 'Boutique Cinemas',
                                'times': ['9:50 PM']}],
                    'location': 'Boulevard Riyadh City'}],
  'title': ['ليلو وستيتش ( مدبلج بالمصري )',
            'LILO AND STITCH (EGYPTIAN DUBBED)']},
 {'city': 'Riyadh',
  'duration': '1 h 44m',
  'genres': ['Horror'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['9:40 PM', '12:10 AM']}],
                    'location': 'Park Avenue'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['8:40 PM', '11:30 PM', '2:10 AM']}],
                    'location': 'The View'},
                   {'cinema': [{'cinema': 'Boutique Cinemas',
                                'times': ['9:15 PM']}],
                    'location': 'muvi Boutique - Tala Mall'},
                   {'cinema': [{'cinema': 'Muvi Suites', 'times': ['2:10 AM']},
                               {'cinema': 'Standard',
                                'times': ['8:20 PM', '2:00 AM']}],
                    'location': 'U Walk'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['7:50 PM', '1:50 AM']}],
                    'location': 'Al Hamra Mall'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['9:00 PM', '11:00 PM', '1:30 AM']}],
                    'location': 'Salaam Mall'},
                   {'cinema': [{'cinema': 'Muvi Suites',
                                'times': ['8:50 PM', '11:30 PM']},
                               {'cinema': 'Standard',
                                'times': ['7:30 PM',
                                          '9:15 PM',
                                          '10:00 PM',
                                          '11:45 PM']}],
                    'location': 'Nakheel Mall'}],
  'title': ['فاينل ديستينيشن: بلودلاينز', 'FINAL DESTINATION: BLOODLINES']},
 {'city': 'Riyadh',
  'duration': '2 h 12m',
  'genres': ['Drama', 'Comedy'],
  'language': 'ARABIC',
  'rating': 'R15',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['8:10 PM', '11:10 PM', '2:10 AM']}],
                    'location': 'Park Avenue'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['1:55 AM']}],
                    'location': 'The View'},
                   {'cinema': [{'cinema': 'Boutique Cinemas',
                                'times': ['1:10 AM']}],
                    'location': 'muvi Boutique - Tala Mall'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['2:10 AM']}],
                    'location': 'Salaam Mall'}],
  'title': ['فخر السويدي ( سعودي )', 'FAKHR AL SUWAIDI (ARABIC)']},
 {'city': 'Riyadh',
  'duration': '1 h 50m',
  'genres': ['Comedy', 'Action'],
  'language': 'ARABIC',
  'rating': 'PG15',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['7:30 PM', '1:10 AM']}],
                    'location': 'Park Avenue'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['11:25 PM']}],
                    'location': 'The View'},
                   {'cinema': [{'cinema': 'Muvi Suites', 'times': ['8:40 PM']},
                               {'cinema': 'Standard', 'times': ['1:10 AM']}],
                    'location': 'U Walk'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['8:30 PM']}],
                    'location': 'Salaam Mall'},
                   {'cinema': [{'cinema': 'Muvi Suites', 'times': ['8:00 PM']},
                               {'cinema': 'Standard', 'times': ['1:55 AM']}],
                    'location': 'Nakheel Mall'}],
  'title': ['اسعاف ( سعودي )', 'ESAAF (ARABIC)']},
 {'city': 'Riyadh',
  'duration': '1 h 40m',
  'genres': ['Comedy'],
  'language': 'ARABIC',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['10:10 PM']}],
                    'location': 'Park Avenue'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['8:00 PM', '10:45 PM', '1:30 AM']}],
                    'location': 'The View'},
                   {'cinema': [{'cinema': 'Boutique Cinemas',
                                'times': ['10:30 PM']}],
                    'location': 'muvi Boutique - Tala Mall'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['10:20 PM']}],
                    'location': 'U Walk'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['12:00 AM']}],
                    'location': 'Al Hamra Mall'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['9:10 PM']}],
                    'location': 'Salaam Mall'},
                   {'cinema': [{'cinema': 'Muvi Suites', 'times': ['2:00 AM']},
                               {'cinema': 'Standard', 'times': ['1:00 AM']}],
                    'location': 'Nakheel Mall'}],
  'title': ['سيكو سيكو (عربي)', 'SIKO SIKO (ARABIC)']},
 {'city': 'Riyadh',
  'duration': '1 h 44m',
  'genres': ['Drama', 'Horror'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['8:30 PM', '2:10 AM']}],
                    'location': 'Park Avenue'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['8:50 PM', '2:00 AM']}],
                    'location': 'The View'}],
  'title': ['انتل دون', 'UNTIL DAWN']},
 {'city': 'Riyadh',
  'duration': '2 h 11m',
  'genres': ['Action'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['11:10 PM']}],
                    'location': 'Park Avenue'}],
  'title': ['ذا أكاونتنت 2', 'THE ACCOUNTANT 2']},
 {'city': 'Riyadh',
  'duration': '2 h 17m',
  'genres': ['Horror', 'Thriller', 'Drama'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['10:50 PM']}],
                    'location': 'U Walk'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['2:10 AM']}],
                    'location': 'Nakheel Mall'}],
  'title': ['سينرس', 'SINNERS']},
 {'city': 'Riyadh',
  'duration': '2 h 35m',
  'genres': [],
  'language': '',
  'rating': 'R15 .',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['12:15 AM']}],
                    'location': 'The View'}],
  'title': ['بهول شاك ماف (هندي)', 'BHOOL CHUK MAAF (HINDI)']},
 {'city': 'Riyadh',
  'duration': '2 h 27m',
  'genres': ['Thriller'],
  'language': 'MALAYALAM',
  'rating': 'R15',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['8:30 PM', '11:45 PM']}],
                    'location': 'The View'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['12:30 AM']}],
                    'location': 'Salaam Mall'}],
  'title': ['ناريفيتا (مالايالام)', 'NARIVETTA (MALAYALAM)']},
 {'city': 'Jeddah',
  'duration': '2 h 50m',
  'genres': ['Adventure', 'Action', 'Thriller'],
  'language': 'ENGLISH',
  'rating': 'R15',
  'show_details': [{'cinema': [{'cinema': 'IMAX',
                                'times': ['10:00 PM', '1:40 AM']},
                               {'cinema': '', 'times': ['10:40 PM', '2:10 AM']},
                               {'cinema': 'Muvi Suites',
                                'times': ['7:20 PM',
                                          '9:20 PM',
                                          '11:30 PM',
                                          '1:30 AM']},
                               {'cinema': 'Standard',
                                'times': ['7:50 PM',
                                          '8:50 PM',
                                          '11:50 PM',
                                          '12:40 AM']}],
                    'location': 'Mall of Arabia'},
                   {'cinema': [{'cinema': 'XPERIENCE',
                                'times': ['8:30 PM', '12:10 AM']},
                               {'cinema': 'Standard',
                                'times': ['7:30 PM',
                                          '9:10 PM',
                                          '9:50 PM',
                                          '10:20 PM',
                                          '11:10 PM',
                                          '12:50 AM']}],
                    'location': 'The Village Jeddah'},
                   {'cinema': [{'cinema': 'Muvi Suites',
                                'times': ['10:00 PM', '1:20 AM', '1:45 AM']}],
                    'location': 'Atelier La Vie'},
                   {'cinema': [{'cinema': 'XPERIENCE',
                                'times': ['9:45 PM', '1:30 AM']},
                               {'cinema': 'Standard',
                                'times': ['8:00 PM',
                                          '9:00 PM',
                                          '11:45 PM',
                                          '12:45 AM',
                                          '2:10 AM']}],
                    'location': 'Yasmin Mall'},
                   {'cinema': [{'cinema': 'ScreenX',
                                'times': ['8:30 PM', '12:15 AM']},
                               {'cinema': 'XPERIENCE',
                                'times': ['9:20 PM', '1:00 AM']},
                               {'cinema': 'Standard',
                                'times': ['7:45 PM', '10:00 PM', '1:45 AM']}],
                    'location': 'Aziz Mall'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['9:40 PM', '10:30 PM', '2:10 AM']}],
                    'location': 'Haifa Mall'}],
  'title': ['ميشن أيمبوسيبول: ذا فاينل ريكونينغ',
            'MISSION: IMPOSSIBLE - THE FINAL RECKONING']},
 {'city': 'Jeddah',
  'duration': '1 h 48m',
  'genres': ['Comedy', 'Adventure', 'Family'],
  'language': 'ENGLISH',
  'rating': '',
  'show_details': [{'cinema': [{'cinema': 'Muvi Suites',
                                'times': ['10:50 PM', '1:00 AM']},
                               {'cinema': 'Muvi Junior', 'times': ['1:30 AM']},
                               {'cinema': 'Standard',
                                'times': ['8:50 PM', '11:30 PM']}],
                    'location': 'Mall of Arabia'},
                   {'cinema': [{'cinema': 'Muvi Junior', 'times': ['7:45 PM']},
                               {'cinema': 'Standard',
                                'times': ['8:50 PM', '11:30 PM', '2:10 AM']}],
                    'location': 'The Village Jeddah'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['9:15 PM']}],
                    'location': 'Yasmin Mall'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['7:30 PM',
                                          '9:00 PM',
                                          '11:30 PM',
                                          '2:00 AM']}],
                    'location': 'Aziz Mall'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['7:40 PM', '10:15 PM']}],
                    'location': 'Haifa Mall'}],
  'title': ['ليلو وستيتش', 'LILO AND STITCH']},
 {'city': 'Jeddah',
  'duration': '1 h 48m',
  'genres': ['Family', 'Adventure', 'Comedy'],
  'language': 'EGYPTIAN',
  'rating': '',
  'show_details': [{'cinema': [{'cinema': 'Muvi Junior',
                                'times': ['8:10 PM', '10:50 PM']},
                               {'cinema': 'Standard',
                                'times': ['11:50 PM', '2:10 AM']}],
                    'location': 'Mall of Arabia'},
                   {'cinema': [{'cinema': 'Muvi Junior',
                                'times': ['10:30 PM', '1:10 AM']}],
                    'location': 'The Village Jeddah'},
                   {'cinema': [{'cinema': 'Muvi Suites',
                                'times': ['11:45 PM']}],
                    'location': 'Atelier La Vie'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['10:00 PM']}],
                    'location': 'Yasmin Mall'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['9:45 PM', '11:15 PM', '12:15 AM']}],
                    'location': 'Aziz Mall'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['7:30 PM', '8:20 PM', '1:00 AM']}],
                    'location': 'Haifa Mall'}],
  'title': ['ليلو وستيتش ( مدبلج بالمصري )',
            'LILO AND STITCH (EGYPTIAN DUBBED)']},
 {'city': 'Jeddah',
  'duration': '1 h 44m',
  'genres': ['Horror'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'XPERIENCE',
                                'times': ['7:20 PM', '10:20 PM', '1:00 AM']},
                               {'cinema': 'Standard', 'times': ['9:20 PM']}],
                    'location': 'Mall of Arabia'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['8:50 PM', '11:30 PM', '2:00 AM']}],
                    'location': 'The Village Jeddah'},
                   {'cinema': [{'cinema': 'Muvi Suites',
                                'times': ['9:20 PM', '10:50 PM']}],
                    'location': 'Atelier La Vie'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['9:10 PM', '11:40 PM', '12:30 AM']}],
                    'location': 'Yasmin Mall'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['9:20 PM', '11:45 PM', '2:10 AM']}],
                    'location': 'Aziz Mall'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['10:15 PM', '12:45 AM', '1:30 AM']}],
                    'location': 'Haifa Mall'}],
  'title': ['فاينل ديستينيشن: بلودلاينز', 'FINAL DESTINATION: BLOODLINES']},
 {'city': 'Jeddah',
  'duration': '2 h 12m',
  'genres': ['Drama', 'Comedy'],
  'language': 'ARABIC',
  'rating': 'R15',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['12:30 AM']}],
                    'location': 'The Village Jeddah'}],
  'title': ['فخر السويدي ( سعودي )', 'FAKHR AL SUWAIDI (ARABIC)']},
 {'city': 'Jeddah',
  'duration': '2 h 6m',
  'genres': ['Superhero', 'Action'],
  'language': 'ENGLISH',
  'rating': 'PG15',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['10:40 PM']}],
                    'location': 'Mall of Arabia'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['10:15 PM']}],
                    'location': 'Yasmin Mall'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['1:50 AM']}],
                    'location': 'Aziz Mall'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['8:30 PM']}],
                    'location': 'Haifa Mall'}],
  'title': ['ثاندربولتس', 'THUNDERBOLTS']},
 {'city': 'Jeddah',
  'duration': '1 h 50m',
  'genres': ['Action', 'Comedy'],
  'language': 'ARABIC',
  'rating': 'PG15',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['7:40 PM', '11:10 PM', '1:20 AM']}],
                    'location': 'Mall of Arabia'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['9:50 PM']}],
                    'location': 'The Village Jeddah'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['7:30 PM', '10:10 PM', '1:00 AM']}],
                    'location': 'Yasmin Mall'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['1:15 AM']}],
                    'location': 'Aziz Mall'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['11:00 PM', '1:45 AM']}],
                    'location': 'Haifa Mall'}],
  'title': ['اسعاف ( سعودي )', 'ESAAF (ARABIC)']},
 {'city': 'Jeddah',
  'duration': '1 h 40m',
  'genres': ['Comedy'],
  'language': 'ARABIC',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Muvi Suites', 'times': ['8:40 PM']},
                               {'cinema': 'Standard',
                                'times': ['8:10 PM',
                                          '10:00 PM',
                                          '12:45 AM',
                                          '2:00 AM']}],
                    'location': 'Mall of Arabia'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['8:00 PM', '10:50 PM', '1:40 AM']}],
                    'location': 'The Village Jeddah'},
                   {'cinema': [{'cinema': 'Muvi Suites', 'times': ['2:15 AM']}],
                    'location': 'Atelier La Vie'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['8:45 PM',
                                          '11:30 PM',
                                          '1:00 AM',
                                          '2:10 AM']}],
                    'location': 'Yasmin Mall'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['9:00 PM', '11:40 PM', '2:15 AM']}],
                    'location': 'Aziz Mall'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['8:00 PM', '10:45 PM', '1:30 AM']}],
                    'location': 'Haifa Mall'}],
  'title': ['سيكو سيكو (عربي)', 'SIKO SIKO (ARABIC)']},
 {'city': 'Jeddah',
  'duration': '1 h 45m',
  'genres': ['Comedy'],
  'language': 'ARABIC',
  'rating': 'PG12',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['7:30 PM']}],
                    'location': 'Yasmin Mall'}],
  'title': ['شباب البومب 2 ( عربي )', 'SHABAB AL BOMB 2 (ARABIC)']},
 {'city': 'Jeddah',
  'duration': '1 h 44m',
  'genres': ['Horror', 'Drama'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['2:10 AM']}],
                    'location': 'Mall of Arabia'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['1:15 AM']}],
                    'location': 'Yasmin Mall'},
                   {'cinema': [{'cinema': 'Standard',
                                'times': ['11:30 PM', '2:00 AM']}],
                    'location': 'Haifa Mall'}],
  'title': ['انتل دون', 'UNTIL DAWN']},
 {'city': 'Jeddah',
  'duration': '2 h 17m',
  'genres': ['Drama', 'Thriller', 'Horror'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['8:30 PM', '11:30 PM']}],
                    'location': 'Mall of Arabia'},
                   {'cinema': [{'cinema': 'Standard', 'times': ['10:05 PM']}],
                    'location': 'Aziz Mall'}],
  'title': ['سينرس', 'SINNERS']},
 {'city': 'Dhahran',
  'duration': '2 h 50m',
  'genres': ['Adventure', 'Action', 'Thriller'],
  'language': 'ENGLISH',
  'rating': 'R15',
  'show_details': [{'cinema': [{'cinema': 'ScreenX', 'times': ['11:15 PM']},
                               {'cinema': 'Muvi Suites',
                                'times': ['10:00 PM', '11:30 PM', '2:00 AM']},
                               {'cinema': 'Dolby Cinema®',
                                'times': ['10:15 PM', '2:00 AM']},
                               {'cinema': 'Standard',
                                'times': ['7:30 PM',
                                          '8:30 PM',
                                          '9:15 PM',
                                          '12:15 AM',
                                          '1:00 AM']}],
                    'location': 'Mall of Dhahran'}],
  'title': ['ميشن أيمبوسيبول: ذا فاينل ريكونينغ',
            'MISSION: IMPOSSIBLE - THE FINAL RECKONING']},
 {'city': 'Dhahran',
  'duration': '1 h 48m',
  'genres': ['Comedy', 'Adventure', 'Family'],
  'language': 'ENGLISH',
  'rating': '',
  'show_details': [{'cinema': [{'cinema': 'Muvi Suites', 'times': ['1:35 AM']},
                               {'cinema': 'Standard',
                                'times': ['8:15 PM', '11:00 PM', '1:45 AM']}],
                    'location': 'Mall of Dhahran'}],
  'title': ['ليلو وستيتش', 'LILO AND STITCH']},
 {'city': 'Dhahran',
  'duration': '1 h 48m',
  'genres': ['Family', 'Adventure', 'Comedy'],
  'language': 'EGYPTIAN',
  'rating': '',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['7:40 PM', '8:30 PM', '9:30 PM']}],
                    'location': 'Mall of Dhahran'}],
  'title': ['ليلو وستيتش ( مدبلج بالمصري )',
            'LILO AND STITCH (EGYPTIAN DUBBED)']},
 {'city': 'Dhahran',
  'duration': '1 h 44m',
  'genres': ['Horror'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Muvi Suites',
                                'times': ['8:20 PM', '11:00 PM']},
                               {'cinema': 'Standard',
                                'times': ['9:30 PM',
                                          '10:30 PM',
                                          '12:15 AM',
                                          '1:15 AM']}],
                    'location': 'Mall of Dhahran'}],
  'title': ['فاينل ديستينيشن: بلودلاينز', 'FINAL DESTINATION: BLOODLINES']},
 {'city': 'Dhahran',
  'duration': '2 h 12m',
  'genres': ['Drama', 'Comedy'],
  'language': 'ARABIC',
  'rating': 'R15',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['11:15 PM', '2:10 AM']}],
                    'location': 'Mall of Dhahran'}],
  'title': ['فخر السويدي ( سعودي )', 'FAKHR AL SUWAIDI (ARABIC)']},
 {'city': 'Dhahran',
  'duration': '2 h 6m',
  'genres': ['Superhero', 'Action'],
  'language': 'ENGLISH',
  'rating': 'PG15',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['8:45 PM', '11:45 PM']}],
                    'location': 'Mall of Dhahran'}],
  'title': ['ثاندربولتس', 'THUNDERBOLTS']},
 {'city': 'Dhahran',
  'duration': '1 h 50m',
  'genres': ['Action', 'Comedy'],
  'language': 'ARABIC',
  'rating': 'PG15',
  'show_details': [{'cinema': [{'cinema': 'Muvi Suites', 'times': ['8:45 PM']},
                               {'cinema': 'Standard',
                                'times': ['7:45 PM',
                                          '8:40 PM',
                                          '10:30 PM',
                                          '11:15 PM',
                                          '1:15 AM',
                                          '1:50 AM']}],
                    'location': 'Mall of Dhahran'}],
  'title': ['اسعاف ( سعودي )', 'ESAAF (ARABIC)']},
 {'city': 'Dhahran',
  'duration': '1 h 40m',
  'genres': ['Comedy'],
  'language': 'ARABIC',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['8:00 PM',
                                          '9:45 PM',
                                          '10:45 PM',
                                          '12:30 AM',
                                          '1:30 AM']}],
                    'location': 'Mall of Dhahran'}],
  'title': ['سيكو سيكو (عربي)', 'SIKO SIKO (ARABIC)']},
 {'city': 'Dhahran',
  'duration': '1 h 45m',
  'genres': ['Comedy'],
  'language': 'ARABIC',
  'rating': 'PG12',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['10:45 PM']}],
                    'location': 'Mall of Dhahran'}],
  'title': ['شباب البومب 2 ( عربي )', 'SHABAB AL BOMB 2 (ARABIC)']},
 {'city': 'Dhahran',
  'duration': '1 h 44m',
  'genres': ['Horror', 'Drama'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['8:00 PM', '1:30 AM']}],
                    'location': 'Mall of Dhahran'}],
  'title': ['انتل دون', 'UNTIL DAWN']},
 {'city': 'Dhahran',
  'duration': '2 h 11m',
  'genres': ['Action'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['12:30 AM']}],
                    'location': 'Mall of Dhahran'}],
  'title': ['ذا أكاونتنت 2', 'THE ACCOUNTANT 2']},
 {'city': 'Dammam',
  'duration': '2 h 50m',
  'genres': ['Adventure', 'Action', 'Thriller'],
  'language': 'ENGLISH',
  'rating': 'R15',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['8:05 PM',
                                          '9:10 PM',
                                          '10:00 PM',
                                          '10:35 PM',
                                          '11:40 PM',
                                          '12:45 AM']}],
                    'location': 'Nakheel Mall Dammam'}],
  'title': ['ميشن أيمبوسيبول: ذا فاينل ريكونينغ',
            'MISSION: IMPOSSIBLE - THE FINAL RECKONING']},
 {'city': 'Dammam',
  'duration': '1 h 48m',
  'genres': ['Comedy', 'Adventure', 'Family'],
  'language': 'ENGLISH',
  'rating': '',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['9:00 PM', '11:30 PM']}],
                    'location': 'Nakheel Mall Dammam'}],
  'title': ['ليلو وستيتش', 'LILO AND STITCH']},
 {'city': 'Dammam',
  'duration': '1 h 48m',
  'genres': ['Family', 'Adventure', 'Comedy'],
  'language': 'EGYPTIAN',
  'rating': '',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['7:30 PM', '10:00 PM']}],
                    'location': 'Nakheel Mall Dammam'}],
  'title': ['ليلو وستيتش ( مدبلج بالمصري )',
            'LILO AND STITCH (EGYPTIAN DUBBED)']},
 {'city': 'Dammam',
  'duration': '1 h 44m',
  'genres': ['Horror'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['9:00 PM', '11:30 PM', '1:55 AM']}],
                    'location': 'Nakheel Mall Dammam'}],
  'title': ['فاينل ديستينيشن: بلودلاينز', 'FINAL DESTINATION: BLOODLINES']},
 {'city': 'Dammam',
  'duration': '1 h 50m',
  'genres': ['Comedy', 'Action'],
  'language': 'ARABIC',
  'rating': 'PG15',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['2:00 AM']}],
                    'location': 'Nakheel Mall Dammam'}],
  'title': ['اسعاف ( سعودي )', 'ESAAF (ARABIC)']},
 {'city': 'Dammam',
  'duration': '1 h 40m',
  'genres': ['Comedy'],
  'language': 'ARABIC',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['12:30 AM']}],
                    'location': 'Nakheel Mall Dammam'}],
  'title': ['سيكو سيكو (عربي)', 'SIKO SIKO (ARABIC)']},
 {'city': 'Al Hofuf',
  'duration': '2 h 50m',
  'genres': ['Adventure', 'Action', 'Thriller'],
  'language': 'ENGLISH',
  'rating': 'R15',
  'show_details': [{'cinema': [{'cinema': 'XPERIENCE',
                                'times': ['8:20 PM', '12:00 AM']},
                               {'cinema': 'Standard',
                                'times': ['7:30 PM',
                                          '9:15 PM',
                                          '10:15 PM',
                                          '11:15 PM',
                                          '1:00 AM']}],
                    'location': 'Al Ahsa Mall'}],
  'title': ['ميشن أيمبوسيبول: ذا فاينل ريكونينغ',
            'MISSION: IMPOSSIBLE - THE FINAL RECKONING']},
 {'city': 'Al Hofuf',
  'duration': '1 h 48m',
  'genres': ['Comedy', 'Adventure', 'Family'],
  'language': 'ENGLISH',
  'rating': '',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['9:30 PM', '11:55 PM']}],
                    'location': 'Al Ahsa Mall'}],
  'title': ['ليلو وستيتش', 'LILO AND STITCH']},
 {'city': 'Al Hofuf',
  'duration': '1 h 48m',
  'genres': ['Family', 'Adventure', 'Comedy'],
  'language': 'EGYPTIAN',
  'rating': '',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['8:40 PM', '11:10 PM']}],
                    'location': 'Al Ahsa Mall'}],
  'title': ['ليلو وستيتش ( مدبلج بالمصري )',
            'LILO AND STITCH (EGYPTIAN DUBBED)']},
 {'city': 'Al Hofuf',
  'duration': '1 h 44m',
  'genres': ['Horror'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['8:45 PM', '11:10 PM', '1:40 AM']}],
                    'location': 'Al Ahsa Mall'}],
  'title': ['فاينل ديستينيشن: بلودلاينز', 'FINAL DESTINATION: BLOODLINES']},
 {'city': 'Al Hofuf',
  'duration': '1 h 50m',
  'genres': ['Comedy', 'Action'],
  'language': 'ARABIC',
  'rating': 'PG15',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['1:45 AM']}],
                    'location': 'Al Ahsa Mall'}],
  'title': ['اسعاف ( سعودي )', 'ESAAF (ARABIC)']},
 {'city': 'Al Hofuf',
  'duration': '1 h 40m',
  'genres': ['Comedy'],
  'language': 'ARABIC',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['7:30 PM', '10:15 PM', '1:00 AM']}],
                    'location': 'Al Ahsa Mall'}],
  'title': ['سيكو سيكو (عربي)', 'SIKO SIKO (ARABIC)']},
 {'city': 'Al Hofuf',
  'duration': '1 h 44m',
  'genres': ['Drama', 'Horror'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['2:15 AM']}],
                    'location': 'Al Ahsa Mall'}],
  'title': ['انتل دون', 'UNTIL DAWN']},
 {'city': 'Al Hofuf',
  'duration': '2 h 17m',
  'genres': ['Drama', 'Thriller', 'Horror'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['1:50 AM']}],
                    'location': 'Al Ahsa Mall'}],
  'title': ['سينرس', 'SINNERS']},
 {'city': 'Al Jubail',
  'duration': '2 h 50m',
  'genres': ['Adventure', 'Action', 'Thriller'],
  'language': 'ENGLISH',
  'rating': 'R15',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['9:00 PM', '12:45 AM']}],
                    'location': 'Jubail Mall'}],
  'title': ['ميشن أيمبوسيبول: ذا فاينل ريكونينغ',
            'MISSION: IMPOSSIBLE - THE FINAL RECKONING']},
 {'city': 'Al Jubail',
  'duration': '1 h 48m',
  'genres': ['Family', 'Adventure', 'Comedy'],
  'language': 'ENGLISH',
  'rating': '',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['8:50 PM']}],
                    'location': 'Jubail Mall'}],
  'title': ['ليلو وستيتش', 'LILO AND STITCH']},
 {'city': 'Al Jubail',
  'duration': '1 h 44m',
  'genres': ['Horror'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['9:40 PM', '12:15 AM']}],
                    'location': 'Jubail Mall'}],
  'title': ['فاينل ديستينيشن: بلودلاينز', 'FINAL DESTINATION: BLOODLINES']},
 {'city': 'Al Jubail',
  'duration': '1 h 50m',
  'genres': ['Comedy', 'Action'],
  'language': 'ARABIC',
  'rating': 'PG15',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['11:45 PM']}],
                    'location': 'Jubail Mall'}],
  'title': ['اسعاف ( سعودي )', 'ESAAF (ARABIC)']},
 {'city': 'Al Jubail',
  'duration': '2 h 35m',
  'genres': [],
  'language': '',
  'rating': 'R15 .',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['8:00 PM', '11:20 PM']}],
                    'location': 'Jubail Mall'}],
  'title': ['بهول شاك ماف (هندي)', 'BHOOL CHUK MAAF (HINDI)']},
 {'city': 'Al Jubail',
  'duration': '2 h 27m',
  'genres': ['Thriller'],
  'language': 'MALAYALAM',
  'rating': 'R15',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['8:15 PM', '11:30 PM']}],
                    'location': 'Jubail Mall'}],
  'title': ['ناريفيتا (مالايالام)', 'NARIVETTA (MALAYALAM)']},
 {'city': 'Buraydah',
  'duration': '2 h 50m',
  'genres': ['Adventure', 'Action', 'Thriller'],
  'language': 'ENGLISH',
  'rating': 'R15',
  'show_details': [{'cinema': [{'cinema': 'XPERIENCE',
                                'times': ['8:20 PM', '12:00 AM']},
                               {'cinema': 'Standard',
                                'times': ['7:30 PM',
                                          '10:10 PM',
                                          '11:10 PM',
                                          '1:30 AM']}],
                    'location': 'Nakheel Plaza Buraydah'}],
  'title': ['ميشن أيمبوسيبول: ذا فاينل ريكونينغ',
            'MISSION: IMPOSSIBLE - THE FINAL RECKONING']},
 {'city': 'Buraydah',
  'duration': '1 h 48m',
  'genres': ['Family', 'Adventure', 'Comedy'],
  'language': 'ENGLISH',
  'rating': '',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['8:50 PM', '11:30 PM', '12:50 AM']}],
                    'location': 'Nakheel Plaza Buraydah'}],
  'title': ['ليلو وستيتش', 'LILO AND STITCH']},
 {'city': 'Buraydah',
  'duration': '1 h 44m',
  'genres': ['Horror'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['10:50 PM', '2:10 AM']}],
                    'location': 'Nakheel Plaza Buraydah'}],
  'title': ['فاينل ديستينيشن: بلودلاينز', 'FINAL DESTINATION: BLOODLINES']},
 {'city': 'Buraydah',
  'duration': '2 h 12m',
  'genres': ['Comedy', 'Drama'],
  'language': 'ARABIC',
  'rating': 'R15',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['9:50 PM']}],
                    'location': 'Nakheel Plaza Buraydah'}],
  'title': ['فخر السويدي ( سعودي )', 'FAKHR AL SUWAIDI (ARABIC)']},
 {'city': 'Buraydah',
  'duration': '1 h 50m',
  'genres': ['Action', 'Comedy'],
  'language': 'ARABIC',
  'rating': 'PG15',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['8:00 PM', '1:50 AM']}],
                    'location': 'Nakheel Plaza Buraydah'}],
  'title': ['اسعاف ( سعودي )', 'ESAAF (ARABIC)']},
 {'city': 'Unayzah',
  'duration': '2 h 50m',
  'genres': ['Adventure', 'Action', 'Thriller'],
  'language': 'ENGLISH',
  'rating': 'R15',
  'show_details': [],
  'title': ['ميشن أيمبوسيبول: ذا فاينل ريكونينغ',
            'MISSION: IMPOSSIBLE - THE FINAL RECKONING']},
 {'city': 'Unayzah',
  'duration': '1 h 48m',
  'genres': ['Comedy', 'Adventure', 'Family'],
  'language': 'ENGLISH',
  'rating': '',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['8:50 PM']}],
                    'location': 'The Boulevard Unaizah'}],
  'title': ['ليلو وستيتش', 'LILO AND STITCH']},
 {'city': 'Unayzah',
  'duration': '1 h 48m',
  'genres': ['Family', 'Adventure', 'Comedy'],
  'language': 'EGYPTIAN',
  'rating': '',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['11:25 PM']}],
                    'location': 'The Boulevard Unaizah'}],
  'title': ['ليلو وستيتش ( مدبلج بالمصري )',
            'LILO AND STITCH (EGYPTIAN DUBBED)']},
 {'city': 'Unayzah',
  'duration': '1 h 44m',
  'genres': ['Horror'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['8:30 PM', '11:00 PM', '1:30 AM']}],
                    'location': 'The Boulevard Unaizah'}],
  'title': ['فاينل ديستينيشن: بلودلاينز', 'FINAL DESTINATION: BLOODLINES']},
 {'city': 'Unayzah',
  'duration': '2 h 12m',
  'genres': ['Comedy', 'Drama'],
  'language': 'ARABIC',
  'rating': 'R15',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['9:45 PM', '12:45 AM']}],
                    'location': 'The Boulevard Unaizah'}],
  'title': ['فخر السويدي ( سعودي )', 'FAKHR AL SUWAIDI (ARABIC)']},
 {'city': 'Unayzah',
  'duration': '2 h 6m',
  'genres': ['Superhero', 'Action'],
  'language': 'ENGLISH',
  'rating': 'PG15',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['9:15 PM', '2:00 AM']}],
                    'location': 'The Boulevard Unaizah'}],
  'title': ['ثاندربولتس', 'THUNDERBOLTS']},
 {'city': 'Unayzah',
  'duration': '1 h 40m',
  'genres': ['Comedy'],
  'language': 'ARABIC',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard',
                                'times': ['9:00 PM', '11:45 PM']}],
                    'location': 'The Boulevard Unaizah'}],
  'title': ['سيكو سيكو (عربي)', 'SIKO SIKO (ARABIC)']},
 {'city': 'Unayzah',
  'duration': '2 h 17m',
  'genres': ['Thriller', 'Horror', 'Drama'],
  'language': 'ENGLISH',
  'rating': 'R18',
  'show_details': [{'cinema': [{'cinema': 'Standard', 'times': ['12:30 AM']}],
                    'location': 'The Boulevard Unaizah'}],
  'title': ['سينرس', 'SINNERS']}]